accounts/urls.py
from django.urls import path
from .views import SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
]

articles/urls.py
from django.urls import path
from .views import (
  ArticlesListView, 
  ArticleDetailView,
  ArticleCreateView,
  ArticleUpdateView,
  ArticleDeleteView
  )

urlpatterns = [
  path('', ArticlesListView.as_view(), name='articles_list'),
  path('<int:pk>/', ArticleDetailView.as_view(), name="article_details"),
  path('new/', ArticleCreateView.as_view(), name="article_new"),
  path('<int:pk>/edit/', ArticleUpdateView.as_view(), name="article_update"),
  path('<int:pk>/delete/', ArticleDeleteView.as_view(), name="article_delete"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
    path('articles/', include('articles.urls')),
] 

pages/urls.py
from django.urls import path
from .views import HomePageView

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    department = models.CharField(max_length=512, null=True, blank=True)
    role = models.CharField(max_length=256, null=True, blank=True)

articles/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

class Article(models.Model):
    title = models.CharField(max_length=256)
    body = models.TextField()
    author = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE
    )
    created_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('article_details', args=[self.id])

pages/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ('department', 'role')


class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm):
        model = CustomUser
        fields = UserChangeForm.Meta.fields

accounts/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy
from .forms import CustomUserCreationForm


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

articles/views.py
from articles.models import Article
from django.views.generic import ListView, DetailView
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

# Create your views here.

class ArticlesListView(ListView):
  template_name = "articles/articles_list.html"
  model = Article

class ArticleDetailView(DetailView):
  template_name = "articles/article_details.html"
  model = Article

class ArticleCreateView(LoginRequiredMixin, CreateView):
  template_name = 'articles/new_article.html'
  model = Article
  fields = ['title', 'author', 'body']

class ArticleUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
  template_name = 'articles/article_update.html'
  model = Article
  fields = ['title', 'body']
  
  def test_func(self):
    obj = self.get_object()
    return obj.author == self.request.user

class ArticleDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
  template_name = 'articles/article_delete.html'
  model = Article
  success_url = reverse_lazy('articles_list')

  def test_func(self):
    obj = self.get_object()
    return obj.author == self.request.user

pages/views.py
from django.views.generic import TemplateView

# Create your views here.

class HomePageView(TemplateView):
    template_name = "index.html"

templates/articles/article_delete.html
{% extends 'base.html' %}

{% block title %}Delete{% endblock title %}

{% block content %}
<h1>!!! Danger !!!</h1>
<p>Are you sure you want to delete this Article?: "{{ article.title }}"</p>
<form method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger " value="Confirm">
</form>
{% endblock content %}

templates/articles/article_details.html
{% extends 'base.html' %}

{% block title %}{{ article.title }}{% endblock title %}

{% block content %}

<div class="card detail-card">
  <div class="card-header">
    <h1>
      {{ article.title }}
    </h1>
  </div>
  <div class="card-body">
    <blockquote class="blockquote mb-0">
      <p>{{ article.body | linebreaks }}</p>
      <footer class="blockquote-footer">
        <cite title="Source Title">{{ article.author | upper }} | {{ article.created_on }}</cite>
      </footer>
    </blockquote>
  </div>
</div>

{% if user.is_authenticated %}
<div class="detail-btn">
  <a type="submit" class="btn btn-secondary" value="Edit" href="{% url 'article_update' article.id %}">Edit</a>
  <a type="submit" class="btn btn-danger" value="Delete" href="{% url 'article_delete' article.id %}">Delete</a>
</div>
{% endif %}
{% endblock content %}

templates/articles/article_update.html
{% extends 'base.html' %}

{% block title %}Editor{% endblock title %}

{% block content %}
<h1>Edit Article</h1>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" class="btn btn-secondary" value="Confirm Changes">
</form>
{% endblock content %}

templates/articles/articles_list.html
{% extends 'base.html' %}

{% block title %}Articles{% endblock title %}

{% block content %}
<div class="articles-list">
  {% for article in article_list %}
  <div class="card">
    <div class="card-header">
      <h1>
        {{ article.title }}
      </h1>
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p>{{ article.body | truncatechars:700 }}</p>
        <footer class="blockquote-footer">
          <a href="{% url 'article_details' article.id %}">
            <cite title="Source Title">{{ article.author | upper }} | {{ article.created_on }}</cite>
          </a>
        </footer>
      </blockquote>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock content %}

templates/articles/new_article.html
{% extends 'base.html' %}

{% block title %}New Article{% endblock title %}

{% block content %}
<h1>New Article</h1>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" class="btn btn-secondary" value="Create">
</form>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}{% endblock title %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Akaya+Telivigala&family=Nova+Mono&family=Warnes&display=swap"
    rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">  
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-link main-name" href="{% url 'home' %}">Ille Diurnal</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown"
        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse">
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'articles_list' %}">Articles</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item"><a class="nav-link" href="{% url 'article_new' %}">New Article</a></li>
          {% endif %}
        </ul>
      </div>
      <div>
        <ul class="navbar-nav">
          {% if user.is_authenticated %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
              data-bs-toggle="dropdown" aria-expanded="false">
              {{ user.username | upper }}
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li><a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a></li>
              <li><a class="dropdown-item" href="{% url 'logout' %}">Log Out</a></li>
            </ul>
          </li>
          {% else %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
              data-bs-toggle="dropdown" aria-expanded="false">
              Log In/Sign Up
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <li><a class="dropdown-item" href="{% url 'login' %}">Log In</a></li>
              <li><a class="dropdown-item" href="{% url 'signup' %}">Sign Up</a></li>
              <li><a class="dropdown-item" href="{% url 'password_reset' %}">Reset Password</a></li>
            </ul>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  <div>
    {% block content %}
    {% endblock content %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>
</body>

</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}Home{% endblock title %}

{% block content %}
<div class="welcome">
  <h1>Ille Diurnal</h1>
  <p>Welcome! Click the Articles link above to view articles from other users. You may also create an account and post your own articles. <br>Gratias Tibi!</p>
</div>
{% endblock content %}